"""initial schema

Revision ID: 25134ce726c1
Revises: 
Create Date: 2026-09-01 09:05:06.768289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25134ce726c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.String(length=100), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('preprocessing_version', sa.Integer(), nullable=False),
    sa.Column('indexing_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry')),
    sa.UniqueConstraint('model_name', 'revision', 'preprocessing_version', 'indexing_version', name='model_version')
    )
    op.create_table('system_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_type'), 'system_events', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recovery_phone', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('uid', name=op.f('uq_users_uid'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('index_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_index_status'), 'media', ['index_status'], unique=False)
    op.create_index(op.f('ix_media_sha256'), 'media', ['sha256'], unique=False)
    op.create_index(op.f('ix_media_status'), 'media', ['status'], unique=False)
    op.create_table('search_feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_feedback'))
    )
    op.create_index(op.f('ix_search_feedback_user_id'), 'search_feedback', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('fine_search_cache',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('interval_start', sa.Float(), nullable=False),
    sa.Column('interval_end', sa.Float(), nullable=False),
    sa.Column('frame_interval', sa.Float(), nullable=False),
    sa.Column('embedding_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_fine_search_cache_media_id_media')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fine_search_cache'))
    )
    op.create_index('ix_fine_cache_interval', 'fine_search_cache', ['media_id', 'interval_start', 'interval_end'], unique=False)
    op.create_index(op.f('ix_fine_search_cache_media_id'), 'fine_search_cache', ['media_id'], unique=False)
    op.create_table('frames',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('frame_type', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_frames_media_id_media')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frames'))
    )
    op.create_index(op.f('ix_frames_embedding_id'), 'frames', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_frames_media_id'), 'frames', ['media_id'], unique=False)
    op.create_index('ix_frames_media_timestamp', 'frames', ['media_id', 'timestamp'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('counters', sa.JSON(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_jobs_media_id_media')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_jobs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_media_id'), 'jobs', ['media_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_media_files_media_id_media')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files'))
    )
    op.create_index(op.f('ix_media_files_media_id'), 'media_files', ['media_id'], unique=False)
    op.create_table('saved_contexts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('match_timestamp', sa.Float(), nullable=True),
    sa.Column('start_timestamp', sa.Float(), nullable=True),
    sa.Column('end_timestamp', sa.Float(), nullable=True),
    sa.Column('context_frames', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_saved_contexts_media_id_media')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_contexts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_contexts'))
    )
    op.create_index(op.f('ix_saved_contexts_media_id'), 'saved_contexts', ['media_id'], unique=False)
    op.create_index(op.f('ix_saved_contexts_user_id'), 'saved_contexts', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('declared_size', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('received_chunks', sa.Integer(), nullable=False),
    sa.Column('received_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_uploads_media_id_media')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_uploads_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index(op.f('ix_uploads_owner_id'), 'uploads', ['owner_id'], unique=False)
    op.create_index(op.f('ix_uploads_status'), 'uploads', ['status'], unique=False)
    op.create_table('fine_search_intervals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('interval_start', sa.Float(), nullable=False),
    sa.Column('interval_end', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_fine_search_intervals_job_id_jobs')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_fine_search_intervals_media_id_media')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fine_search_intervals'))
    )
    op.create_index(op.f('ix_fine_search_intervals_job_id'), 'fine_search_intervals', ['job_id'], unique=False)
    op.create_index(op.f('ix_fine_search_intervals_media_id'), 'fine_search_intervals', ['media_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('upload_chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('upload_id', sa.String(length=32), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_upload_chunks_upload_id_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_chunks')),
    sa.UniqueConstraint('upload_id', 'index', name='upload_chunk')
    )
    op.create_index(op.f('ix_upload_chunks_upload_id'), 'upload_chunks', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_chunks_upload_id'), table_name='upload_chunks')
    op.drop_table('upload_chunks')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_fine_search_intervals_media_id'), table_name='fine_search_intervals')
    op.drop_index(op.f('ix_fine_search_intervals_job_id'), table_name='fine_search_intervals')
    op.drop_table('fine_search_intervals')
    op.drop_index(op.f('ix_uploads_status'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_owner_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_saved_contexts_user_id'), table_name='saved_contexts')
    op.drop_index(op.f('ix_saved_contexts_media_id'), table_name='saved_contexts')
    op.drop_table('saved_contexts')
    op.drop_index(op.f('ix_media_files_media_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_media_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_frames_media_timestamp', table_name='frames')
    op.drop_index(op.f('ix_frames_media_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_embedding_id'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_fine_search_cache_media_id'), table_name='fine_search_cache')
    op.drop_index('ix_fine_cache_interval', table_name='fine_search_cache')
    op.drop_table('fine_search_cache')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_search_feedback_user_id'), table_name='search_feedback')
    op.drop_table('search_feedback')
    op.drop_index(op.f('ix_media_status'), table_name='media')
    op.drop_index(op.f('ix_media_sha256'), table_name='media')
    op.drop_index(op.f('ix_media_index_status'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_events_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
